# Exercise Sheet 1

## Question 1
You and your friend are presented with $7$ boxes. $3$ of the boxes contain delicious chocolates while other $4$ are filled with deadly mushrooms (disguised as delicious chocolates). Both of you will need to select a box and eat what is inside, but you need to decide which of you will go first.

**Question 1.1** In order to increase your chance of eating delicious chocolates, should you choose first or second?\
**Solution.** Let $A$ denote the event of getting chocolate in the first trial.\
Let $B$ denote the event of getting chocolate in the second trial.\
$$P(A) = \frac{3}{7}.$$ According to the law of total probabilities: $$P(B) = P(B \mid A)P(A) + P(B \mid A')P(A')$$ $$\therefore \ P(B) = \frac{2}{6} \cdot \frac{3}{7} + \frac{3}{6} \cdot \frac{4}{7} = \frac{3}{7}$$ $$\therefore \ P(A) = P(B)$$ 
As a result, the chance of eating delicious chocolates remains the same regardless of choosing to go first or second.

**Question 1.2** If you choose first, what is the probability that you eat delicious chocolates, given that your friend also does?\
**Solution.** $$P(A \mid B) = \frac{P(B \mid A) P(A)}{P(B)} = \frac{\frac{2}{6} \cdot \frac{3}{7}}{\frac{3}{7}} = \frac{1}{3}.$$

**Question 1.3** How would your answer to (i) change if there were three of you: yourself and two friends? Answer this without doing any mathematics or algebra, perhaps by referring to examples from this module.\
**Solution.** The answer would not change. This is the same question as the one discussed duringthe lecture where we tried to calculate the probability of the third ball drawn from an urn with 3 black balls and 4 red balls being a black ball. Essentially, the probability always remains the same regardless of the order.

## Question 2
A class consists of $12$ girls and $16$ boys. Jane is one of the girls and Jonathan is one of the boys.

**Question 2.1** In how many ways can we make a group of $2$ girls and $3$ boys?\
   $$\text{Number of ways} = {16 \choose 3}\cdot{12 \choose 2} = 36960.$$

**Question 2.2** What is the probability that Jane is not in that group but Jonathan is?\
   $$P(\text{Jonathan without Jane}) = \frac{{15 \choose 2} \cdot {11 \choose 2}}{\text{Number of ways}} = \frac{5}{32}.$$
   
**Question 2.3** What is the probability that Jonathan is and Jane is not a group of 5 students selected randomly out of the 28?\
**Solution.** Let $E_1$ denote the event that Jonathan is but Jane is not a group of 5 students randomly selected out of the 28. $$P(E_1) = \frac{{26 \choose 4}}{{28 \choose 5}} = \frac{115}{756}.$$

**Question 2.4** What is the probability that there are at least $2$ boys and at least $1$ girl in a randomly selected group of $5$ students?\
**Solution.** Let $E_2$ denote the event that there are at least $2$ boys and at least $1$ girl in a randomly selected group of $5$ students. $$P(E_2) = \frac{{16 \choose 2} \cdot {12 \choose 3} + {16 \choose 3} \cdot {12 \choose 2} + {16 \choose 4} \cdot {12 \choose 1}}{{28 \choose 5}} = \frac{85200}{98280} \approx 0.8669.$$
